"""Initial Migration

Revision ID: 3941f39472b3
Revises: 1fcd4ff32846
Create Date: 2022-03-10 18:03:31.974681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3941f39472b3'
down_revision = '1fcd4ff32846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_pic_path')
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
