"""Initial Migration

Revision ID: 5841e29d4147
Revises: d3aadfb085ed
Create Date: 2022-03-08 17:26:43.677033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5841e29d4147'
down_revision = 'd3aadfb085ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'pass_secure')
    # ### end Alembic commands ###
