"""Initial Migration

Revision ID: 5f0d9f376a23
Revises: 5841e29d4147
Create Date: 2022-03-08 17:41:21.429996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0d9f376a23'
down_revision = '5841e29d4147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastname', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastname')
    # ### end Alembic commands ###
